# Generated by Django 5.1.4 on 2025-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_attribute_alter_role_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('userName', models.EmailField(max_length=254)),
                ('birthDate', models.DateField(max_length=30)),
                ('contactNumber', models.CharField(default='', max_length=15)),
            ],
            options={
                'db_table': 'sos_employee',
            },
        ),
    ]
