# Generated by Django 5.1.4 on 2025-01-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiativeName', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('startDate', models.DateField(max_length=25)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_initiative',
            },
        ),
    ]
