# Generated by Django 5.1.4 on 2025-02-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0004_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
