# Generated by Django 5.1.4 on 2025-02-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0005_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('AppointmentDate', models.DateField(max_length=50)),
                ('contactNumber', models.CharField(max_length=15)),
                ('illness', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_client',
            },
        ),
    ]
