# Generated by Django 5.1.4 on 2025-02-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0006_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='AppointmentDate',
            new_name='appointmentDate',
        ),
    ]
