# Generated by Django 5.1.4 on 2025-02-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0007_rename_appointmentdate_client_appointmentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('birthDate', models.DateField(max_length=50)),
                ('contactNumber', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sos_physician',
            },
        ),
    ]
